from typing import List, Dict, Optional
from pydantic import BaseModel, Field
from enum import Enum

# Knowledge Layer schema

class CodeNode(BaseModel):
    """Represents a single logical chunk of the enterprise codebase."""
    node_id: str = Field(
        description="Unique UUID for the AST chunk."
    )
    file_path: str = Field(
        description="Relative path in the repository (e.g., src/auth/jwt.py)."
    )
    symbol_name: str = Field(
        description="Name of the function or class."
    )
    source_code: str = Field(
        description="The actual raw text of the code chunk."
    )
    child_nodes: List[str] = Field(
        default_factory=list, 
        description="UUIDs of functions that this node explicitly calls. These dependencies should typically be mocked."
    )
    parent_nodes: List[str] = Field(
        default_factory=list, 
        description="UUIDs of functions throughout the repository that call this node. Use these to understand realistic input structures."
    )

# Execution Layer schema

class NetworkMode(str, Enum):
    NONE = "none"
    BRIDGE = "bridge"

class BuildSource(str, Enum):
    SUNDER_DOCKERFILE = "sunder_dockerfile"
    SUNDER_COMPOSE = "sunder_compose"

class SandboxProfile(BaseModel):
    """Configuration object managed by the TUI and enforced by the Execution Layer."""
    network_mode: NetworkMode = Field(
        default=NetworkMode.NONE,
        description="Determines if the container has network access. 'none' enforces absolute isolation."
    )
    memory_limit: str = Field(
        default="512m",
        description="Maximum RAM allocated to the test container (e.g., '256m', '1g')."
    )
    cpu_quota: float = Field(
        default=1.0,
        description="Fractional CPU cores allocated to the test container (e.g., 1.0 for one core)."
    )
    timeout_seconds: int = Field(
        default=30,
        description="Maximum allowed execution time in seconds before the container is forcibly killed by the host."
    )
    environment_vars: Dict[str, str] = Field(
        default_factory=dict,
        description="Key-value pairs of environment variables injected into the container (e.g., configuration overrides or poison pill credentials)."
    )
    build_source: BuildSource = Field(
        default=BuildSource.SUNDER_DOCKERFILE,
        description="Specifies whether to build from a custom Dockerfile or a docker-compose configuration."
    )

class ExecutionReport(BaseModel):
    """Raw data returned from the Docker Sandbox."""
    exit_code: int = Field(
        description="The integer exit code returned by the test execution. 0 indicates a clean exit, >0 indicates a crash or assertion failure."
    )
    stdout: str = Field(
        description="The standard terminal output generated during the test run."
    )
    stderr: str = Field(
        description="The error traces, panic logs, or warnings generated during the test run."
    )

# Orchestration Layer schema

class AgentMode(str, Enum):
    BASELINE = "baseline"
    ADVERSARIAL = "adversarial"

class BlastRadiusContext(BaseModel):
    """The packaged context delivered to the Orchestration Layer."""
    target_node: CodeNode = Field(
        description="The primary function or class being tested by the agent."
    )
    children: List[CodeNode] = Field(
        description="Dependencies and functions explicitly called by the target node. These should be mocked."
    )
    parents: List[CodeNode] = Field(
        description="Functions that call the target node. These provide examples of realistic input structures and usage patterns."
    )

class EnvironmentState(BaseModel):
    """Persistent data object generated during Baseline Mode."""
    auth_headers: Dict[str, str] = Field(
        default_factory=dict,
        description="Generated JWTs, session IDs, or Bearer tokens required to bypass authentication checks."
    )
    seeded_entities: Dict[str, str] = Field(
        default_factory=dict,
        description="Key-value map of mock database IDs initialized during the Baseline test (e.g., {'test_user_id': 'uuid-123'})."
    )
    cookies: Dict[str, str] = Field(
        default_factory=dict, 
        description="Session cookies required for web-based auth barriers."
    )
    mock_credentials: Dict[str, str] = Field(
        default_factory=dict, 
        description="Plaintext username/passwords created by the Baseline test for the AI to use in payloads."
    )
    dynamic_endpoints: Dict[str, str] = Field(
        default_factory=dict, 
        description="Host/Port mappings if docker-compose spins up dependencies dynamically (e.g., {'redis': 'localhost:6379'})."
    )
    ephemeral_files: List[str] = Field(
        default_factory=list, 
        description="Paths to temporary files generated by the Baseline test that the Adversary test might need to read."
    )

class AgentStatus(str, Enum):
    PENDING = "pending"
    COMPLETED = "completed"
    FAILED = "failed"

class SunderAgentState(BaseModel):
    """The mutable state object passed between nodes in the LangGraph state machine."""
    mode: AgentMode = Field(
        description="The current operational mode of the agent ('baseline' for state seeding, 'adversarial' for fuzzing)."
    )
    context: BlastRadiusContext = Field(
        description="The structural code context defining the target and its relational blast radius."
    )
    sandbox_config: SandboxProfile = Field(
        description="The strict execution constraints applied to the zero-trust Docker sandbox."
    )
    env_state: EnvironmentState = Field(
        default_factory=EnvironmentState,
        description="The persistent state containing dynamic credentials, mock data, and routing endpoints passed between test iterations."
    )
    current_test_script: str = Field(
        default="",
        description="The raw code of the latest AI-generated test script."
    )
    execution_report: Optional[ExecutionReport] = Field(
        default=None,
        description="The structured output from the most recent sandbox run. Null if no execution has occurred yet."
    )
    evaluator_feedback: str = Field(
        default="",
        description="Actionable synthesis provided by the Evaluator node to guide the Coder node in fixing bugs or adapting the next payload."
    )
    retry_count: int = Field(
        default=0,
        description="The current iteration number of the agentic loop. Used by the router to prevent infinite loops."
    )
    status: AgentStatus = Field(
        default=AgentStatus.PENDING,
        description="The overarching status of the LangGraph state machine execution."
    )

class EvaluationVerdict(str, Enum):
    """The internal conclusion reached by the LangGraph Evaluator node."""
    SYSTEM_SECURE = "SYSTEM_SECURE"
    VULNERABILITY_FOUND = "VULNERABILITY_FOUND"
    SYNTAX_ERROR = "SYNTAX_ERROR"